In [1]:
#Ke Feng 
#DSC478 Programming Machine Learning
#Assignment 4 Question 1

In [46]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing 
from sklearn.cluster import KMeans
from sklearn.metrics import completeness_score, homogeneity_score
from sklearn import decomposition

In [47]:
###a. Load the Data and normalization
#Load the image matrix 
segdata=pd.read_csv('segmentation_data.txt', header=None)
segdata.head()

0      1   2    3    4         5         6         7         8   \
0  110.0  189.0   9  0.0  0.0  1.000000  0.666667  1.222222  1.186342   
1   86.0  187.0   9  0.0  0.0  1.111111  0.720082  1.444444  0.750309   
2  225.0  244.0   9  0.0  0.0  3.388889  2.195113  3.000000  1.520234   
3   47.0  232.0   9  0.0  0.0  1.277778  1.254621  1.000000  0.894427   
4   97.0  186.0   9  0.0  0.0  1.166667  0.691215  1.166667  1.005540   

          9          10         11         12        13         14         15  \
0  12.925926  10.888889   9.222222  18.666668 -6.111111 -11.111111  17.222221   
1  13.740741  11.666667  10.333334  19.222221 -6.222222 -10.222222  16.444445   
2  12.259259  10.333334   9.333334  17.111110 -5.777778  -8.777778  14.555555   
3  12.703704  11.000000   9.000000  18.111110 -5.111111 -11.111111  16.222221   
4  15.592592  13.888889  11.777778  21.111110 -5.111111 -11.444445  16.555555   

          16        17        18  
0  18.666668  0.508139  1.910864  
1  19.222221  0.463329  1.941465  
2  17.111110  0.480149  1.987902  
3  18.111110  0.500966  1.875362  
4  21.111110  0.442661  1.863654

In [48]:
#load the class
segclass=pd.read_csv('segmentation_classes.txt', sep='\t', header=None, names=['name','value'])
segclass.head()

name  value
0  GRASS      0
1  GRASS      0
2  GRASS      0
3  GRASS      0
4  GRASS      0

In [49]:
#load the names
segname=pd.read_csv('segmentation_names.txt', header=None, names=['names'])
segname.head()

names
0   REGION-CENTROID-COL
1   REGION-CENTROID-ROW
2    REGION-PIXEL-COUNT
3  SHORT-LINE-DENSITY-5
4  SHORT-LINE-DENSITY-2

In [50]:
#transform the data into numpy array
segdata1=np.array(segdata)
segclass1=np.array(segclass)
#label location indexer with name 
segname1=segname.iloc[:,0] #starting from zero
segname1

0      REGION-CENTROID-COL
1      REGION-CENTROID-ROW
2       REGION-PIXEL-COUNT
3     SHORT-LINE-DENSITY-5
4     SHORT-LINE-DENSITY-2
5               VEDGE-MEAN
6                 VEDGE-SD
7               HEDGE-MEAN
8                 HEDGE-SD
9           INTENSITY-MEAN
10             RAWRED-MEAN
11            RAWBLUE-MEAN
12           RAWGREEN-MEAN
13              EXRED-MEAN
14             EXBLUE-MEAN
15            EXGREEN-MEAN
16              VALUE-MEAN
17         SATURATION-MEAN
18                HUE-MEAN
Name: names, dtype: object

In [51]:
#Normalization (Max-Min Scaling)
minmax=preprocessing.MinMaxScaler().fit(segdata1)
segnorm=minmax.transform(segdata1)
segnorm

array([[0.43083004, 0.74166667, 0.        , ..., 0.12371135, 0.50813884,
        0.83184923],
       [0.33596838, 0.73333333, 0.        , ..., 0.12739322, 0.46332908,
        0.83698646],
       [0.88537549, 0.97083333, 0.        , ..., 0.11340205, 0.48014903,
        0.84478233],
       ...,
       [0.50197628, 0.625     , 0.        , ..., 0.07216495, 0.5409177 ,
        0.17591546],
       [0.58893281, 0.6125    , 0.        , ..., 0.08100147, 0.50308645,
        0.18478933],
       [0.48616601, 0.62916667, 0.        , ..., 0.09646539, 0.4799313 ,
        0.17037463]])

In [52]:
###b. Performing K-means clustering 
#Use scikit-learn to perform k-means, k=7   
kmeans=KMeans(n_clusters=7)
kmeans.fit(segnorm)  #This automatically calculate things based on Euclidian distance 

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [53]:
#check class labels
labels=kmeans.labels_
print(labels)

[0 0 0 ... 4 4 3]


In [54]:
#print centroids 
centroids=kmeans.cluster_centers_
centroidsT=centroids.T

In [55]:
#print into a certain format (include the cluster name)
pd.DataFrame(centroidsT, index = segname1, columns = ['C1', 'C2','C3','C4','C5',' C6','C7'])

C1        C2        C3        C4        C5  \
names                                                                    
REGION-CENTROID-COL   0.513994  0.254169  0.535099  0.256103  0.770674   
REGION-CENTROID-ROW   0.808937  0.459974  0.150167  0.393468  0.425215   
REGION-PIXEL-COUNT    0.000000  0.000000  0.000000  0.000000  0.000000   
SHORT-LINE-DENSITY-5  0.077441  0.026256  0.027778  0.074510  0.013978   
SHORT-LINE-DENSITY-2  0.005051  0.013699  0.001667  0.019118  0.022581   
VEDGE-MEAN            0.054474  0.037274  0.030228  0.077343  0.040237   
VEDGE-SD              0.001407  0.002364  0.000543  0.004100  0.002989   
HEDGE-MEAN            0.046335  0.027874  0.026766  0.060574  0.023122   
HEDGE-SD              0.001401  0.002017  0.000587  0.004967  0.002088   
INTENSITY-MEAN        0.108790  0.026013  0.823246  0.148187  0.041138   
RAWRED-MEAN           0.091403  0.017925  0.779716  0.138085  0.035005   
RAWBLUE-MEAN          0.092414  0.042306  0.894170  0.185160  0.058340   
RAWGREEN-MEAN         0.142676  0.016504  0.788761  0.118539  0.028766   
EXRED-MEAN            0.679161  0.769800  0.270665  0.716906  0.778473   
EXBLUE-MEAN           0.079002  0.216011  0.666373  0.344014  0.223939   
EXGREEN-MEAN          0.821287  0.508117  0.289386  0.355458  0.486509   
VALUE-MEAN            0.134901  0.043295  0.894170  0.185413  0.059295   
SATURATION-MEAN       0.414491  0.801687  0.211804  0.411986  0.538181   
HUE-MEAN              0.892333  0.181153  0.125066  0.201890  0.243969   

                            C6        C7  
names                                     
REGION-CENTROID-COL   0.302506  0.750696  
REGION-CENTROID-ROW   0.530862  0.534564  
REGION-PIXEL-COUNT    0.000000  0.000000  
SHORT-LINE-DENSITY-5  0.052260  0.040000  
SHORT-LINE-DENSITY-2  0.046610  0.038462  
VEDGE-MEAN            0.100817  0.114419  
VEDGE-SD              0.009420  0.019301  
HEDGE-MEAN            0.083972  0.109240  
HEDGE-SD              0.011043  0.017999  
INTENSITY-MEAN        0.400608  0.300955  
RAWRED-MEAN           0.370347  0.279908  
RAWBLUE-MEAN          0.472461  0.352738  
RAWGREEN-MEAN         0.353036  0.265920  
EXRED-MEAN            0.497146  0.592572  
EXBLUE-MEAN           0.570882  0.451124  
EXGREEN-MEAN          0.213054  0.309158  
VALUE-MEAN            0.472461  0.352822  
SATURATION-MEAN       0.302263  0.302342  
HUE-MEAN              0.163879  0.164764

In [56]:
#Complete Scores 
cscore = completeness_score(segclass['value'], labels)
print(cscore)

0.6131870124853012


In [57]:
#Hemogenity Values 
hscore = homogeneity_score(segclass['value'], labels)
print(hscore)

0.6115021163370863


In [61]:
###c. Perform PCA 
#Perform PCAs   
pca=decomposition.PCA(n_components=4)
dpca=pca.fit(segdata1).transform(segdata)
print(dpca)

[[-84.65245102  -4.42822449  -8.88238053 -39.00957207]
 [-84.34818706 -28.54013911  -7.57830109 -39.77329513]
 [-96.16386629 115.47120969 -17.9039471  -78.89504679]
 ...
 [-78.74145774  10.28016375  -9.02800177  -5.84264659]
 [-72.93546019  31.65864413  -9.31241009  -2.42595138]
 [-72.70095839   6.09336327  -7.91153763  -9.90339635]]


In [63]:
#Print explained ratio
print(pca.explained_variance_ratio_)  #This is when ratio reaches above 95%. 

[0.4171365  0.24216705 0.18910341 0.10403878]


In [69]:
#print the reduced dimensiosn
dpcaframe=pd.DataFrame(dpca, columns = ['PC1', 'PC2', 'PC3', 'PC4'])
dpcaframe.head()

PC1         PC2        PC3        PC4
0  -84.652451   -4.428224  -8.882381 -39.009572
1  -84.348187  -28.540139  -7.578301 -39.773295
2  -96.163866  115.471210 -17.903947 -78.895047
3 -107.484284  -62.142089  -6.927148 -82.941026
4  -79.607929  -17.947676  -8.239140 -39.513479

In [70]:
###d. Perform Clustering again on PCA dimension reduced data
#Fit K-means with PCA dimension reduced data
kmeans.fit(dpca)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [75]:
#print cluster lables
labels=kmeans.labels_
print(labels)

[0 0 4 ... 4 4 4]


In [77]:
#print centroids
centroids=kmeans.cluster_centers_  
print(centroids)

[[-49.10902183 -47.14978669  -4.04114603 -66.86257491]
 [164.30263442 -73.01705782  -6.94330726   0.80914698]
 [ 53.37283766  50.84930814 731.14733422 -14.24007736]
 [-51.61777445 -63.2091209    2.76858241  30.8192427 ]
 [-60.70624919  73.93007085  -9.10514271  18.46271688]
 [ 20.51623091  55.95816127  -2.10223186 -18.65743094]
 [209.94575005  48.1312783  -16.18429329   4.47926133]]


In [78]:
#form the new centroids into frame
pd.DataFrame(kmeans.cluster_centers_.T, index = ['PC 1', 'PC 2', 'PC 3', 'PC 4'], columns = ['Cluster 1', 'Cluster 2','Cluster 3','Cluster 4','Cluster 5',' Cluster 6','Cluster 7'])

Cluster 1   Cluster 2   Cluster 3  Cluster 4  Cluster 5   Cluster 6  \
PC 1 -49.109022  164.302634   53.372838 -51.617774 -60.706249   20.516231   
PC 2 -47.149787  -73.017058   50.849308 -63.209121  73.930071   55.958161   
PC 3  -4.041146   -6.943307  731.147334   2.768582  -9.105143   -2.102232   
PC 4 -66.862575    0.809147  -14.240077  30.819243  18.462717  -18.657431   

       Cluster 7  
PC 1  209.945750  
PC 2   48.131278  
PC 3  -16.184293  
PC 4    4.479261

In [79]:
#The completeness scores 
cscore = completeness_score(segclass['value'], labels)
print(cscore)

0.5449633844698588


In [81]:
#The honogeneity scores 
hscore = homogeneity_score(segclass['value'], labels)
print(hscore)

0.4832065291324426
